{{- if .Values.github.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.github.tokenSecretName }}
  labels:
    {{- include "secflow-collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.github.tokenSecretKey }}: {{ .Values.github.token | b64enc }}
{{- end }}